export type Booking = {
  age: number;
  airline: string;
  arrival_time: string;
  company: string;
  cost: number;
  departure_time: string;
  duration: string;
  email: string;
  extra_bags: number;
  flight_from: string;
  flight_to: string;
  meal_choice: string;
  name: string;
  passport_number: number;
  PK: string;
  priority_boarding: boolean;
  SK: string;
  timestamp: string;
  transaction_id: string;
};
